### ISSUE TITLE
Add some details about setup to the docs?

### ISSUE THREAD

**Issue by maelle** [andrie/mailmerge#3]
Thanks for this neat package!

I was starting to use it and convinced I had set up gmailr correctly since I recently used it... I had forgotten to run `gmailr::gm_auth_configure()` :grimacing: I was wondering:

* whether mailmerge should catch and render gmailr error message? I didn't see it, I added a browser() inside mailmerge.
* whether the docs could refer to the docs of gmailr reg setup so that my stupid mistake would be harder to make?

**Comment by andrie** [comment]
I've fixed this in #4
